name: "solismon"
description: "Solis Modbus Monitor based on  NosIreland /solismon3"
version: "1.0.7"
slug: "solismon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
services:
  - mqtt:want
options:
  MQTT_SERVER_IP: "192.168.0.160"
  MQTT_SERVER_USERNAME: mqtt
  MQTT_SERVER_PASSWORD: mqtt
  MQTT_PORT: 1833
  MQTT_TOPIC: "solis/METRICS" 
  MQTT_SERVER_ENABLE: false
  IP_INVERTER1: "192.168.0.128"
  INVERTER1_DONGLE_SERIAL: "123456789"
  IP_INVERTER2: "192.168.0.128"
  INVERTER2_DONGLE_SERIAL: "123456789"
schema:
  MQTT_SERVER_IP: str
  MQTT_SERVER_USERNAME: str
  MQTT_SERVER_PASSWORD: password
  MQTT_PORT: int
  MQTT_TOPIC: str 
  MQTT_SERVER_ENABLE: bool
  IP_INVERTER1: str
  INVERTER1_DONGLE_SERIAL: str
  IP_INVERTER2: str
  INVERTER2_DONGLE_SERIAL: str

